### ISSUE TITLE
Problem using Samba share

### ISSUE THREAD

**Issue by szabof-JS** [vargaLaszlo/nodevagrant#1]
When I tried to connect to the vagrant samba share (`devs`) I got the following error (Win 7 Professional 64 bit Hungarian):
  "A megadott kiszolgáló nem tudja végrehajtani a kért műveletet."

On the linux side I tried to restart samba. Here you can see the (error) messages:
"
$ service smbd restart
stop: Rejected send message, 1 matched rules; type="method_call", sender=":1.15" (uid=1000 pid=2546 comm="stop smbd ") interface="com.ubuntu.Upstart0_6.Job" member="Stop" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.16" (uid=1000 pid=2540 comm="start smbd ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
sed: -e expression #2, char 4: unterminated `s' command

$ service nmbd restart
stop: Rejected send message, 1 matched rules; type="method_call", sender=":1.18" (uid=1000 pid=2563 comm="stop nmbd ") interface="com.ubuntu.Upstart0_6.Job" member="Stop" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
start: Rejected send message, 1 matched rules; type="method_call", sender=":1.19" (uid=1000 pid=2557 comm="start nmbd ") interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)" requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1 comm="/sbin/init ")
sed: -e expression #2, char 4: unterminated `s' command
"

**Comment by vargaLaszlo** [comment]
Open windos file manager > Network > Hit F5 > Wait until "NODEVAGRANT" appiers under "Computers", if not, shut down your other virtualbox machines, or disble windows firewall.
